Homework 30 Kubernetes 3
Otus-DevOps-2017-11/mrgreyves_microservices pull request #13
Opened 2018-04-01 19:47 UTC by mrgreyves

Выполнил домашнее задание.

2018-05-02 13:31 UTC, vitkhab requested changes
Приложение запускается и работает. Все выглядит хорошо, но конфигурация не полная, не хватает описание секрета (сертификата и ключа для ингресса) в виде yaml-конфигурации.

Для зачета ДЗ прошу добавить в PR конфигурацию секрета

2018-05-02 13:31 UTC, vitkhab commented on kubernetes/ui-ingress.yml
> +spec:
Спека не по заданию (не по презентации). Но так тоже работает.
Не обратил внимание или по другим причинам решил сделать так?

2018-05-02 15:52 UTC, vitkhab approved these changes
Коллеги в чате обратили внимание на то, что добавление секрета - это дополнительное задание.

ДЗ принимается и без него.

2018-05-03 11:59 UTC, mrgreyves commented
Виталий, привет! Спасибо за фидбек!)

2018-05-03 12:00 UTC, mrgreyves commented on kubernetes/ui-ingress.yml
> +spec:
Честно, уже и не припомню....

2018-05-03 12:00 UTC, merged