HW 16 docker-3
Otus-DevOps-2017-11/mrgreyves_microservices pull request #3
Opened 2018-02-03 15:09 UTC by mrgreyves

Здравствуйте! Выполнил дз 16. Пришлось с ним повозиться. Первая проблема это сборка образа для UI. Не в какую не хотел собираться. Вываливался с ошибкой Cannot allocate memory. Немного поигрался с этой ошибкой и в итоге пересоздал инстанс с докер машин с большим количеством оперативки. Использовал шаблон инстанса g1-small. Так же немного засел со сборкой образа из alpine.

2018-02-07 09:17 UTC, serjs requested changes

2018-02-07 09:17 UTC, serjs commented on ui/Docker_small
> +ENV APP_HOME /app \
Привет! Я думаю что ENV с backslash (\) работать не будет, т.к. он задаст переменной APP_HOME значение трех следующих строк, ты проверял это?

2018-02-07 09:27 UTC, mrgreyves commented on ui/Docker_small
> +ENV APP_HOME /app \
Привет, Сергей! Проверял, все собиралось.

2018-02-07 15:32 UTC, mrgreyves commented on ui/Docker_small
> +ENV APP_HOME /app \
Перепроверил, ты оказался полностью прав, образ то собирался вот только ничего не работало))) Внес правки и перепроверил. Теперь работает. Немного подсмотрел вариант у Алексея Степаненко и Андрея Сысоева.

2018-02-11 13:50 UTC, serjs approved these changes

2018-02-11 13:50 UTC, serjs commented on README.md
> +ENV APP_HOME /app \
Поправь readme по части ENV переменных тоже

2018-02-11 14:07 UTC, merged